POST http://localhost:3333/event
Content-Type: application/json

{
  "title": "nlw unite 2", 
  "details" : null,
  "maximumAttendees": 20
}

###

POST http://localhost:3333/attendee/16a9ce0d-05c7-4558-8e60-0aa5a4ad51ed/register
Content-Type: application/json

{
  "name": "Gustavo", 
  "email" : "gustavo@codifica.dev"
}

###
GET http://localhost:3333/event/16a9ce0d-05c7-4558-8e60-0aa5a4ad51ed