POST http://localhost:3333/event
Content-Type: application/json

{
  "title": "nlw unite 2", 
  "details" : null,
  "maximumAttendees": 20
}

###

POST http://localhost:3333/attendee/ea35b095-31d1-461d-b872-6cb4e0cace1a/register
Content-Type: application/json

{
  "name": "Gustavo", 
  "email" : "gustavosalviato8@gmail.com"
}

###
GET http://localhost:3333/event/16a9ce0d-05c7-4558-8e60-0aa5a4ad51ed


###
GET http://localhost:3333/attendee/1/badge


###
GET http://localhost:3333/attendees/3/checkIn

###
GET http://localhost:3333/events/ea35b095-31d1-461d-b872-6cb4e0cace1a/attendees